[theme]

# Primary accent for interactive elements
primaryColor = '#4169e1'

# Background color for the main content area
backgroundColor = '#FFFFFF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#3D2C8D'

# Color used for almost all text
textColor = '#FFFFFF'
