[theme]

# Primary accent for interactive elements
primaryColor = '##FFFFFF'

# Background color for the main content area
backgroundColor = '#87CEEB'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#3D2C8D'

# Color used for almost all text
textColor = '#FFFFFF'
